#cards
COPPER = "copper"
SILVER = "silver"
GOLD = "gold"

CURSE = "curse"

ESTATE = "estate"
DUCHY = "duchy"
PROVINCE = "province"

CELLAR = "cellar"
FEAST = "feast"
MARKET = "market"
MILITIA = "militia"
MINE = "mine"
MOAT = "moat"
REMODEL = "remodel"
SMITHY = "smithy"
VILLAGE = "village"
WORKSHOP = "workshop"
WOODCUTTER = "woodcutter"

# card lists
TREASURE_CARDS = [COPPER, SILVER, GOLD]
VICTORY_CARDS = [ESTATE, DUCHY, PROVINCE]
CURSE_CARDS = [CURSE]
SCORE_CARDS = VICTORY_CARDS + CURSE_CARDS
FIRST_GAME_ACTION_CARDS = [CELLAR, FEAST, MARKET, MILITIA, MINE, MOAT, REMODEL, SMITHY, VILLAGE, WORKSHOP, WOODCUTTER]
ALL_FIRST_GAME_CARDS = TREASURE_CARDS + VICTORY_CARDS + FIRST_GAME_ACTION_CARDS

# game sets
FIRST_GAME = "First Game"
